/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as OutrosServicosRouteImport } from './routes/outros-servicos'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ExtratoRouteImport } from './routes/extrato'
import { Route as IndexRouteImport } from './routes/index'

const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OutrosServicosRoute = OutrosServicosRouteImport.update({
  id: '/outros-servicos',
  path: '/outros-servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratoRoute = ExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extrato': typeof ExtratoRoute
  '/investimentos': typeof InvestimentosRoute
  '/outros-servicos': typeof OutrosServicosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extrato': typeof ExtratoRoute
  '/investimentos': typeof InvestimentosRoute
  '/outros-servicos': typeof OutrosServicosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extrato': typeof ExtratoRoute
  '/investimentos': typeof InvestimentosRoute
  '/outros-servicos': typeof OutrosServicosRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extrato'
    | '/investimentos'
    | '/outros-servicos'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extrato' | '/investimentos' | '/outros-servicos' | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/extrato'
    | '/investimentos'
    | '/outros-servicos'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtratoRoute: typeof ExtratoRoute
  InvestimentosRoute: typeof InvestimentosRoute
  OutrosServicosRoute: typeof OutrosServicosRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outros-servicos': {
      id: '/outros-servicos'
      path: '/outros-servicos'
      fullPath: '/outros-servicos'
      preLoaderRoute: typeof OutrosServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrato': {
      id: '/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof ExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtratoRoute: ExtratoRoute,
  InvestimentosRoute: InvestimentosRoute,
  OutrosServicosRoute: OutrosServicosRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
